"use strict";
/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Mon Oct 09 2017 09:36:31 GMT-0400 (EDT)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ENV = {};

//# sourceMappingURL=data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFwcC9zaGFyZWQvY29uc3RhbnQvZW52LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7O0dBU0c7O0FBSVUsUUFBQSxHQUFHLEdBQVcsRUFDMUIsQ0FBQyIsImZpbGUiOiJhcHAvc2hhcmVkL2NvbnN0YW50L2Vudi5qcyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogVEhJUyBGSUxFIElTIEdFTkVSQVRFRCBieSBgZ3VscCBlbnZgIGNvbW1hbmQgZnJvbSBgZW52Lmpzb25gXG4gKiBHZW5lcmF0ZWQgb24gTW9uIE9jdCAwOSAyMDE3IDA5OjM2OjMxIEdNVC0wNDAwIChFRFQpXG4gKlxuICogTWFrZSBzdXJlIHRoZSBrZXlzIGluIGBlbnYubW9kZWwudHNgIGV4aXN0IGluIGBlbnYuanNvbmBcbiAqIG90aGVyd2lzZSBpdCdsbCB0aHJvdyBtZXNzYWdlIGxpa2UgdGhpc1xuICogUHJvcGVydHkgJzxtaXNzaW5nLWtleT4nIGlzIG1pc3NpbmcgaW4gdHlwZSAne30nXG4gKlxuICogRmVlbCBmcmVlIHRvIG1vZGlmeSBmb3IgZGlyZWN0IHVwZGF0ZXMgaW4gZGV2ZWxvcG1lbnRcbiAqL1xuXG5pbXBvcnQgeyBBcHBFbnYgfSBmcm9tICcuL2Vudi5tb2RlbCc7XG5cbmV4cG9ydCBjb25zdCBFTlY6IEFwcEVudiA9IHtcbn07XG4iXX0=
